export const GET_ALL_STUDENTS_REQUEST = "GET_ALL_STUDENTS_REQUEST";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_FAILURE = "GET_ALL_STUDENTS_FAILURE";
export const GET_STUDENT_BY_ID_REQUEST = "GET_STUDENT_BY_ID_REQUEST";
export const GET_STUDENT_BY_ID_SUCCESS = "GET_STUDENT_BY_ID_SUCCESS";
export const GET_STUDENT_BY_ID_FAILURE = "GET_STUDENT_BY_ID_FAILURE";
export const GET_NATIONALITY_BY_ID_REQUEST = "GET_NATIONALITY_BY_ID_REQUEST";
export const GET_NATIONALITY_BY_ID_SUCCESS = "GET_NATIONALITY_BY_ID_SUCCESS";
export const GET_NATIONALITY_BY_ID_FAILURE = "GET_NATIONALITY_BY_ID_FAILURE";
export const GET_FAMILY_MEMBER_BY_ID_REQUEST =
  "GET_FAMILY_MEMBER_BY_ID_REQUEST";
export const GET_FAMILY_MEMBER_BY_ID_SUCCESS =
  "GET_FAMILY_MEMBER_BY_ID_SUCCESS";
export const GET_FAMILY_MEMBER_BY_ID_FAILURE =
  "GET_FAMILY_MEMBER_BY_ID_FAILURE";
export const DELETE_FAMILY_MEMBER_BY_ID_REQUEST =
  "DELETE_FAMILY_MEMBER_BY_ID_REQUEST";
export const DELETE_FAMILY_MEMBER_BY_ID_SUCCESS =
  "DELETE_FAMILY_MEMBER_BY_ID_SUCCESS";
export const DELETE_FAMILY_MEMBER_BY_ID_FAILURE =
  "DELETE_FAMILY_MEMBER_BY_ID_FAILURE";
export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAILURE = "CREATE_STUDENT_FAILURE";
export const GET_NATIONALITIES_REQUEST = "GET_NATIONALITIES_REQUEST";
export const GET_NATIONALITIES_SUCCESS = "GET_NATIONALITIES_SUCCESS";
export const GET_NATIONALITIES_FAILURE = "GET_NATIONALITIES_FAILURE";
export const UPDATE_NATIONALITY_BY_ID_REQUEST =
  "UPDATE_NATIONALITY_BY_ID_REQUEST";
export const UPDATE_NATIONALITY_BY_ID_SUCCESS =
  "UPDATE_NATIONALITY_BY_ID_SUCCESS";
export const UPDATE_NATIONALITY_BY_ID_FAILURE =
  "UPDATE_NATIONALITY_BY_ID_FAILURE";
export const CREATE_FAMILY_MEMBER_BY_ID_REQUEST =
  "CREATE_FAMILY_MEMBER_BY_ID_REQUEST";
export const CREATE_FAMILY_MEMBER_BY_ID_SUCCESS =
  "CREATE_FAMILY_MEMBER_BY_ID_SUCCESS";
export const CREATE_FAMILY_MEMBER_BY_ID_FAILURE =
  "CREATE_FAMILY_MEMBER_BY_ID_FAILURE";
export const UPDATE_FAMILY_MEMBER_NATIONALITY_BY_ID_REQUEST =
  "UPDATE_FAMILY_MEMBER_NATIONALITY_BY_ID_REQUEST";
export const UPDATE_FAMILY_MEMBER_NATIONALITY_BY_ID_SUCCESS =
  "UPDATE_FAMILY_MEMBER_NATIONALITY_BY_ID_SUCCESS";
export const UPDATE_FAMILY_MEMBER_NATIONALITY_BY_ID_FAILURE =
  "UPDATE_FAMILY_MEMBER_NATIONALITY_BY_ID_FAILURE";
export const UPDATE_STUDENT_BY_ID_REQUEST = "UPDATE_STUDENT_BY_ID_REQUEST";
export const UPDATE_STUDENT_BY_ID_SUCCESS = "UPDATE_STUDENT_BY_ID_SUCCESS";
export const UPDATE_STUDENT_BY_ID_FAILURE = "UPDATE_STUDENT_BY_ID_FAILURE";
export const UPDATE_FAMILY_MEMBER_BY_ID_REQUEST = "UPDATE_FAMILY_MEMBER_BY_ID_REQUEST";
export const UPDATE_FAMILY_MEMBER_BY_ID_SUCCESS = "UPDATE_FAMILY_MEMBER_BY_ID_SUCCESS";
export const UPDATE_FAMILY_MEMBER_BY_ID_FAILURE = "UPDATE_FAMILY_MEMBER_BY_ID_FAILURE";
export const CLEAR_MODAL_STATES = "CLEAR_MODAL_STATES";
export const SET_ROLE_RIGHTS = "SET_ROLE_RIGHTS";
export const SET_ROLE = "SET_ROLE";
export const CLEAR_ALL_STATES = "CLEAR_ALL_STATES";
